[project]
name = "sokoban-llm-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.6.6",
    "loguru>=0.7.3",
    "opik>=1.8.34",
]
